formatter: "markdown table"

output:
  file: "README.md"
  mode: "replace"
  template: |-
    {{ .Content }}

content: |-
  {{ include "../../docs/partials/demo/header.md" }}

  {{ include "docs/intro.md" }}

  {{ .Providers }}

  {{ .Modules }}



  ## Resources

  | Name | Type | Description |
  |------|------|-------------|
  {{- range .Module.Resources }}
  | [{{ .Spec }}]({{ .URL }}) | {{ .GetMode }} | {{ if .Description }}{{ .Description }}{{ else }}n/a{{ end }} |
  {{- end }}


  {{ .Inputs }}

  {{ .Outputs }}

  {{ include "../../docs/partials/footer.md" }}

recursive:
  enabled: false

sort:
  enabled: true
  by: "name"

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
